// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachSubmissionJob = `-- name: AttachSubmissionJob :one
UPDATE job_submissions
SET job_id = $1::bigint
WHERE id = $2 AND status = 'approved'
RETURNING id, submitted_by, url, source, title, company, location, remote, description, posted_at, status, review_reason, reviewed_by, reviewed_at, job_id, created_at, skills, regions, cities, work_mode, salary_min, salary_max, salary_currency, salary_period, employment_type, seniority
`

type AttachSubmissionJobParams struct {
	JobID int64 `json:"job_id"`
	ID    int64 `json:"id"`
}

// Records the minted job on a submission ClaimSubmissionForApproval already claimed.
// Scoped to status='approved', not 'pending' — by this point the claim has already moved
// it there, and the guard exists so this never resurrects a submission some other path
// moved on (in practice unreachable, since only Approve's own claim reaches this status).
func (q *Queries) AttachSubmissionJob(ctx context.Context, arg AttachSubmissionJobParams) (JobSubmission, error) {
	row := q.db.QueryRow(ctx, attachSubmissionJob, arg.JobID, arg.ID)
	var i JobSubmission
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.URL,
		&i.Source,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.Status,
		&i.ReviewReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.JobID,
		&i.CreatedAt,
		&i.Skills,
		&i.Regions,
		&i.Cities,
		&i.WorkMode,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.EmploymentType,
		&i.Seniority,
	)
	return i, err
}

const claimSubmissionForApproval = `-- name: ClaimSubmissionForApproval :one
UPDATE job_submissions
SET status      = 'approved',
    reviewed_by = $1::bigint,
    reviewed_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, submitted_by, url, source, title, company, location, remote, description, posted_at, status, review_reason, reviewed_by, reviewed_at, job_id, created_at, skills, regions, cities, work_mode, salary_min, salary_max, salary_currency, salary_period, employment_type, seniority
`

type ClaimSubmissionForApprovalParams struct {
	ReviewedBy int64 `json:"reviewed_by"`
	ID         int64 `json:"id"`
}

// Claim-first half of approval: atomically flips a pending submission to 'approved' and
// records the reviewing moderator, leaving job_id NULL until AttachSubmissionJob records
// the mint. Scoped to status='pending', so this is the guarded transition a concurrent
// Reject on the same row always loses (whichever call flips the status first wins; the
// other affects 0 rows, mapped to ErrAlreadyDecided by the service). Running this BEFORE
// the mint — rather than marking approved only after, as the single MarkSubmissionApproved
// update used to — closes the race where a concurrent Reject could flip the status between
// the mint and the mark: the job would exist live while the submission stayed 'rejected'
// with no job_id pointing at it.
func (q *Queries) ClaimSubmissionForApproval(ctx context.Context, arg ClaimSubmissionForApprovalParams) (JobSubmission, error) {
	row := q.db.QueryRow(ctx, claimSubmissionForApproval, arg.ReviewedBy, arg.ID)
	var i JobSubmission
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.URL,
		&i.Source,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.Status,
		&i.ReviewReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.JobID,
		&i.CreatedAt,
		&i.Skills,
		&i.Regions,
		&i.Cities,
		&i.WorkMode,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.EmploymentType,
		&i.Seniority,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO job_submissions (
    submitted_by, url, source, title, company, location, remote, description, posted_at,
    skills, regions, cities, work_mode, employment_type, seniority,
    salary_min, salary_max, salary_currency, salary_period
) VALUES (
    $1::bigint, $2, $3, $4,
    $5, $6, $7, $8,
    $9,
    COALESCE($10::text[], '{}'), COALESCE($11::text[], '{}'),
    COALESCE($12::text[], '{}'), $13,
    $14, $15,
    $16, $17, $18, $19
)
RETURNING id, submitted_by, url, source, title, company, location, remote, description, posted_at, status, review_reason, reviewed_by, reviewed_at, job_id, created_at, skills, regions, cities, work_mode, salary_min, salary_max, salary_currency, salary_period, employment_type, seniority
`

type CreateSubmissionParams struct {
	SubmittedBy    int64              `json:"submitted_by"`
	URL            string             `json:"url"`
	Source         string             `json:"source"`
	Title          string             `json:"title"`
	Company        string             `json:"company"`
	Location       string             `json:"location"`
	Remote         bool               `json:"remote"`
	Description    string             `json:"description"`
	PostedAt       pgtype.Timestamptz `json:"posted_at"`
	Skills         []string           `json:"skills"`
	Regions        []string           `json:"regions"`
	Cities         []string           `json:"cities"`
	WorkMode       string             `json:"work_mode"`
	EmploymentType string             `json:"employment_type"`
	Seniority      string             `json:"seniority"`
	SalaryMin      pgtype.Int4        `json:"salary_min"`
	SalaryMax      pgtype.Int4        `json:"salary_max"`
	SalaryCurrency string             `json:"salary_currency"`
	SalaryPeriod   string             `json:"salary_period"`
}

// Insert a user-contributed vacancy into the moderation queue as 'pending'. The partial
// unique index on lower(url) WHERE status='pending' rejects a second pending submission of
// the same URL (the repository maps that unique violation to a 409).
func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (JobSubmission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.SubmittedBy,
		arg.URL,
		arg.Source,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Remote,
		arg.Description,
		arg.PostedAt,
		arg.Skills,
		arg.Regions,
		arg.Cities,
		arg.WorkMode,
		arg.EmploymentType,
		arg.Seniority,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		arg.SalaryPeriod,
	)
	var i JobSubmission
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.URL,
		&i.Source,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.Status,
		&i.ReviewReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.JobID,
		&i.CreatedAt,
		&i.Skills,
		&i.Regions,
		&i.Cities,
		&i.WorkMode,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.EmploymentType,
		&i.Seniority,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, submitted_by, url, source, title, company, location, remote, description, posted_at, status, review_reason, reviewed_by, reviewed_at, job_id, created_at, skills, regions, cities, work_mode, salary_min, salary_max, salary_currency, salary_period, employment_type, seniority FROM job_submissions WHERE id = $1
`

// Load a single submission by id for the review path. The approve/reject flow guards the
// status in the service; the Mark* queries are additionally scoped to status='pending' as
// defense-in-depth against a concurrent second decision.
func (q *Queries) GetSubmission(ctx context.Context, id int64) (JobSubmission, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i JobSubmission
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.URL,
		&i.Source,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.Status,
		&i.ReviewReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.JobID,
		&i.CreatedAt,
		&i.Skills,
		&i.Regions,
		&i.Cities,
		&i.WorkMode,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.EmploymentType,
		&i.Seniority,
	)
	return i, err
}

const listPendingSubmissionURLs = `-- name: ListPendingSubmissionURLs :many
SELECT id, url FROM job_submissions WHERE status = 'pending'
`

type ListPendingSubmissionURLsRow struct {
	ID  int64  `json:"id"`
	URL string `json:"url"`
}

// id+url of every pending submission, used only to find which OTHER pending rows share the
// host being blocked (see RejectAndBlockHost in the submission package): host matching needs
// Go's net/url normalization (see submission.normalizeHost), so this fetches the candidates
// and the caller filters in Go rather than duplicating that normalization in SQL.
func (q *Queries) ListPendingSubmissionURLs(ctx context.Context) ([]ListPendingSubmissionURLsRow, error) {
	rows, err := q.db.Query(ctx, listPendingSubmissionURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingSubmissionURLsRow{}
	for rows.Next() {
		var i ListPendingSubmissionURLsRow
		if err := rows.Scan(&i.ID, &i.URL); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSubmissions = `-- name: ListPendingSubmissions :many
SELECT s.id, s.submitted_by, s.url, s.source, s.title, s.company, s.location, s.remote, s.description, s.posted_at, s.status, s.review_reason, s.reviewed_by, s.reviewed_at, s.job_id, s.created_at, s.skills, s.regions, s.cities, s.work_mode, s.salary_min, s.salary_max, s.salary_currency, s.salary_period, s.employment_type, s.seniority, u.email AS submitter_email
FROM job_submissions s
JOIN users u ON u.id = s.submitted_by
WHERE s.status = 'pending'
ORDER BY s.created_at DESC
LIMIT 500
`

type ListPendingSubmissionsRow struct {
	JobSubmission  JobSubmission `json:"job_submission"`
	SubmitterEmail string        `json:"submitter_email"`
}

// The moderator review queue: pending submissions, newest first, with the submitter's
// email so the moderator can judge provenance. Capped at 500 as a runaway-growth
// guard — far above any plausible backlog; a queue that deep needs bulk triage,
// not a longer page.
// sqlc.embed keeps the submission row as one db.JobSubmission instead of a flat row type
// unrelated to it, so the adapter maps it once (fromRow) rather than re-assembling it here
// (see mentorship.sql's ListBookingsByMentor for the same shape).
func (q *Queries) ListPendingSubmissions(ctx context.Context) ([]ListPendingSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listPendingSubmissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingSubmissionsRow{}
	for rows.Next() {
		var i ListPendingSubmissionsRow
		if err := rows.Scan(
			&i.JobSubmission.ID,
			&i.JobSubmission.SubmittedBy,
			&i.JobSubmission.URL,
			&i.JobSubmission.Source,
			&i.JobSubmission.Title,
			&i.JobSubmission.Company,
			&i.JobSubmission.Location,
			&i.JobSubmission.Remote,
			&i.JobSubmission.Description,
			&i.JobSubmission.PostedAt,
			&i.JobSubmission.Status,
			&i.JobSubmission.ReviewReason,
			&i.JobSubmission.ReviewedBy,
			&i.JobSubmission.ReviewedAt,
			&i.JobSubmission.JobID,
			&i.JobSubmission.CreatedAt,
			&i.JobSubmission.Skills,
			&i.JobSubmission.Regions,
			&i.JobSubmission.Cities,
			&i.JobSubmission.WorkMode,
			&i.JobSubmission.SalaryMin,
			&i.JobSubmission.SalaryMax,
			&i.JobSubmission.SalaryCurrency,
			&i.JobSubmission.SalaryPeriod,
			&i.JobSubmission.EmploymentType,
			&i.JobSubmission.Seniority,
			&i.SubmitterEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUser = `-- name: ListSubmissionsByUser :many
SELECT s.id, s.submitted_by, s.url, s.source, s.title, s.company, s.location, s.remote, s.description, s.posted_at, s.status, s.review_reason, s.reviewed_by, s.reviewed_at, s.job_id, s.created_at, s.skills, s.regions, s.cities, s.work_mode, s.salary_min, s.salary_max, s.salary_currency, s.salary_period, s.employment_type, s.seniority, j.public_slug AS job_slug
FROM job_submissions s
LEFT JOIN jobs j ON j.id = s.job_id
WHERE s.submitted_by = $1
ORDER BY s.created_at DESC
`

type ListSubmissionsByUserRow struct {
	JobSubmission JobSubmission `json:"job_submission"`
	JobSlug       pgtype.Text   `json:"job_slug"`
}

// "My submissions": one user's submissions, newest first, whatever their status.
// LEFT JOIN the minted job (present only once approved) to surface its public_slug,
// so the UI can link an approved submission straight to its live vacancy page.
// sqlc.embed, see ListPendingSubmissions above.
func (q *Queries) ListSubmissionsByUser(ctx context.Context, submittedBy int64) ([]ListSubmissionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByUser, submittedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsByUserRow{}
	for rows.Next() {
		var i ListSubmissionsByUserRow
		if err := rows.Scan(
			&i.JobSubmission.ID,
			&i.JobSubmission.SubmittedBy,
			&i.JobSubmission.URL,
			&i.JobSubmission.Source,
			&i.JobSubmission.Title,
			&i.JobSubmission.Company,
			&i.JobSubmission.Location,
			&i.JobSubmission.Remote,
			&i.JobSubmission.Description,
			&i.JobSubmission.PostedAt,
			&i.JobSubmission.Status,
			&i.JobSubmission.ReviewReason,
			&i.JobSubmission.ReviewedBy,
			&i.JobSubmission.ReviewedAt,
			&i.JobSubmission.JobID,
			&i.JobSubmission.CreatedAt,
			&i.JobSubmission.Skills,
			&i.JobSubmission.Regions,
			&i.JobSubmission.Cities,
			&i.JobSubmission.WorkMode,
			&i.JobSubmission.SalaryMin,
			&i.JobSubmission.SalaryMax,
			&i.JobSubmission.SalaryCurrency,
			&i.JobSubmission.SalaryPeriod,
			&i.JobSubmission.EmploymentType,
			&i.JobSubmission.Seniority,
			&i.JobSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmissionRejected = `-- name: MarkSubmissionRejected :one
UPDATE job_submissions
SET status        = 'rejected',
    reviewed_by   = $1::bigint,
    reviewed_at   = now(),
    review_reason = $2
WHERE id = $3 AND status = 'pending'
RETURNING id, submitted_by, url, source, title, company, location, remote, description, posted_at, status, review_reason, reviewed_by, reviewed_at, job_id, created_at, skills, regions, cities, work_mode, salary_min, salary_max, salary_currency, salary_period, employment_type, seniority
`

type MarkSubmissionRejectedParams struct {
	ReviewedBy   int64  `json:"reviewed_by"`
	ReviewReason string `json:"review_reason"`
	ID           int64  `json:"id"`
}

// Mark a pending submission rejected with an optional reason, recording the deciding
// moderator. Scoped to status='pending' (see ClaimSubmissionForApproval). No job is created.
func (q *Queries) MarkSubmissionRejected(ctx context.Context, arg MarkSubmissionRejectedParams) (JobSubmission, error) {
	row := q.db.QueryRow(ctx, markSubmissionRejected, arg.ReviewedBy, arg.ReviewReason, arg.ID)
	var i JobSubmission
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.URL,
		&i.Source,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.Status,
		&i.ReviewReason,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.JobID,
		&i.CreatedAt,
		&i.Skills,
		&i.Regions,
		&i.Cities,
		&i.WorkMode,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.EmploymentType,
		&i.Seniority,
	)
	return i, err
}

const markSubmissionsRejectedByIDs = `-- name: MarkSubmissionsRejectedByIDs :many
UPDATE job_submissions
SET status        = 'rejected',
    reviewed_by   = $1::bigint,
    reviewed_at   = now(),
    review_reason = $2
WHERE id = ANY($3::bigint[]) AND status = 'pending'
RETURNING id, submitted_by, url, source, title, company, location, remote, description, posted_at, status, review_reason, reviewed_by, reviewed_at, job_id, created_at, skills, regions, cities, work_mode, salary_min, salary_max, salary_currency, salary_period, employment_type, seniority
`

type MarkSubmissionsRejectedByIDsParams struct {
	ReviewedBy   int64   `json:"reviewed_by"`
	ReviewReason string  `json:"review_reason"`
	Ids          []int64 `json:"ids"`
}

// Bulk-reject every given id still pending, recording the same moderator and reason on
// each — the sibling half of RejectAndBlockHost. Scoped to status='pending' like the
// single-row Mark* queries, so a row already decided by the time this runs is left alone.
func (q *Queries) MarkSubmissionsRejectedByIDs(ctx context.Context, arg MarkSubmissionsRejectedByIDsParams) ([]JobSubmission, error) {
	rows, err := q.db.Query(ctx, markSubmissionsRejectedByIDs, arg.ReviewedBy, arg.ReviewReason, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobSubmission{}
	for rows.Next() {
		var i JobSubmission
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.URL,
			&i.Source,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.Status,
			&i.ReviewReason,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.JobID,
			&i.CreatedAt,
			&i.Skills,
			&i.Regions,
			&i.Cities,
			&i.WorkMode,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryPeriod,
			&i.EmploymentType,
			&i.Seniority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
