// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_job_scores.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJevScoreBatch = `-- name: ClaimJevScoreBatch :many
WITH claimable AS (
    SELECT o.id, o.user_id, o.job_id, o.target_version
    FROM job_score_outbox o
    WHERE o.failed_at IS NULL
      AND (o.claimed_at IS NULL
           OR o.claimed_at < now() - make_interval(secs => $1::int))
      AND EXISTS (
          SELECT 1 FROM jobs j
          WHERE j.id = o.job_id AND j.closed_at IS NULL AND j.duplicate_of IS NULL
      )
    ORDER BY o.job_posted_at DESC NULLS LAST, o.job_id DESC
    FOR UPDATE OF o SKIP LOCKED
    LIMIT $2::int
)
UPDATE job_score_outbox o
SET claimed_at = now()
FROM claimable c
WHERE o.id = c.id
RETURNING o.id, o.user_id, o.job_id, o.target_version
`

type ClaimJevScoreBatchParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	BatchSize    int32 `json:"batch_size"`
}

type ClaimJevScoreBatchRow struct {
	ID            int64 `json:"id"`
	UserID        int64 `json:"user_id"`
	JobID         int64 `json:"job_id"`
	TargetVersion int32 `json:"target_version"`
}

// Claim a wave of live, unleased entries for open canonical jobs, freshest first.
func (q *Queries) ClaimJevScoreBatch(ctx context.Context, arg ClaimJevScoreBatchParams) ([]ClaimJevScoreBatchRow, error) {
	rows, err := q.db.Query(ctx, claimJevScoreBatch, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimJevScoreBatchRow{}
	for rows.Next() {
		var i ClaimJevScoreBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.TargetVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countForYou = `-- name: CountForYou :one
SELECT count(*)
FROM user_job_scores s
JOIN jobs j ON j.id = s.job_id
WHERE s.user_id = $1
  AND j.closed_at IS NULL AND j.duplicate_of IS NULL
  AND ($2::text = '' OR s.verdict = $2::text)
  AND s.match_pct >= $3::int
`

type CountForYouParams struct {
	UserID  int64  `json:"user_id"`
	Verdict string `json:"verdict"`
	MinPct  int32  `json:"min_pct"`
}

func (q *Queries) CountForYou(ctx context.Context, arg CountForYouParams) (int64, error) {
	row := q.db.QueryRow(ctx, countForYou, arg.UserID, arg.Verdict, arg.MinPct)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteIneligibleJevScoreOutbox = `-- name: DeleteIneligibleJevScoreOutbox :execrows
DELETE FROM job_score_outbox
WHERE id IN (
    SELECT o.id
    FROM job_score_outbox o
    LEFT JOIN jobs j ON j.id = o.job_id
    WHERE o.failed_at IS NULL
      AND (j.id IS NULL OR j.closed_at IS NOT NULL OR j.duplicate_of IS NOT NULL)
    LIMIT $1::int
)
`

// Reap live entries the claim can never take: job gone/closed/duplicate. Leaves
// dead-lettered rows (failed_at set) alone. Bounded by max_rows.
func (q *Queries) DeleteIneligibleJevScoreOutbox(ctx context.Context, maxRows int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIneligibleJevScoreOutbox, maxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJevScoreEntries = `-- name: DeleteJevScoreEntries :exec
DELETE FROM job_score_outbox WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteJevScoreEntries(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, deleteJevScoreEntries, ids)
	return err
}

const deleteUserScoreOutbox = `-- name: DeleteUserScoreOutbox :exec
DELETE FROM job_score_outbox WHERE user_id = $1
`

// Drop a user's pending queue entries so re-enqueue stamps them with fresh values.
func (q *Queries) DeleteUserScoreOutbox(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserScoreOutbox, userID)
	return err
}

const enqueueJevScoresForProfile = `-- name: EnqueueJevScoresForProfile :execrows
INSERT INTO job_score_outbox (user_id, job_id, target_version, job_posted_at)
SELECT $1::bigint, j.id, $2::int, COALESCE(j.posted_at, j.created_at)
FROM jobs j
WHERE j.closed_at IS NULL
  AND j.duplicate_of IS NULL
  AND j.is_tech IS TRUE
  AND j.description <> ''
  AND j.enriched_at IS NOT NULL
  AND j.category = ANY($3::text[])
  AND (cardinality($4::text[]) = 0 OR j.seniority = ANY($4::text[]))
  AND NOT (j.company_slug = ANY($5::text[]))
  AND NOT (j.source = ANY($6::text[]))
  AND NOT EXISTS (
      SELECT 1 FROM user_job_scores s
      WHERE s.user_id = $1::bigint
        AND s.job_id = j.id
        AND s.score_version = $2::int
        AND s.model = $7::text
        AND s.profile_fingerprint = $8::text
        AND s.cv_uploaded_at IS NOT DISTINCT FROM $9
        AND s.job_content_hash IS NOT DISTINCT FROM j.content_hash
  )
ON CONFLICT (user_id, job_id) DO NOTHING
`

type EnqueueJevScoresForProfileParams struct {
	UserID             int64              `json:"user_id"`
	TargetVersion      int32              `json:"target_version"`
	Specializations    []string           `json:"specializations"`
	Seniorities        []string           `json:"seniorities"`
	ExcludedCompanies  []string           `json:"excluded_companies"`
	ExcludedSources    []string           `json:"excluded_sources"`
	Model              string             `json:"model"`
	ProfileFingerprint string             `json:"profile_fingerprint"`
	CvUploadedAt       pgtype.Timestamptz `json:"cv_uploaded_at"`
}

// Coarse enqueue for one profile: open/tech/enriched jobs whose category and seniority
// match, not excluded, and lacking a FRESH score. The fine hard-blocker gate runs in the
// worker before Jev is called. ON CONFLICT keeps one live entry per (user, job).
func (q *Queries) EnqueueJevScoresForProfile(ctx context.Context, arg EnqueueJevScoresForProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJevScoresForProfile,
		arg.UserID,
		arg.TargetVersion,
		arg.Specializations,
		arg.Seniorities,
		arg.ExcludedCompanies,
		arg.ExcludedSources,
		arg.Model,
		arg.ProfileFingerprint,
		arg.CvUploadedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forYouFeed = `-- name: ForYouFeed :many
SELECT j.public_slug, j.title, j.company, j.company_slug, j.location, j.work_mode,
       j.posted_at, j.closed_at, j.skills,
       s.match_pct, s.verdict, s.has_required_stack, s.fits_level, s.hard_blocker, s.role_category
FROM user_job_scores s
JOIN jobs j ON j.id = s.job_id
WHERE s.user_id = $1
  AND j.closed_at IS NULL AND j.duplicate_of IS NULL
  AND ($2::text = '' OR s.verdict = $2::text)
  AND s.match_pct >= $3::int
ORDER BY s.match_pct DESC, j.id DESC
LIMIT $5::int OFFSET $4::int
`

type ForYouFeedParams struct {
	UserID  int64  `json:"user_id"`
	Verdict string `json:"verdict"`
	MinPct  int32  `json:"min_pct"`
	Off     int32  `json:"off"`
	Lim     int32  `json:"lim"`
}

type ForYouFeedRow struct {
	PublicSlug       string             `json:"public_slug"`
	Title            string             `json:"title"`
	Company          string             `json:"company"`
	CompanySlug      string             `json:"company_slug"`
	Location         string             `json:"location"`
	WorkMode         string             `json:"work_mode"`
	PostedAt         pgtype.Timestamptz `json:"posted_at"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
	Skills           []string           `json:"skills"`
	MatchPct         int16              `json:"match_pct"`
	Verdict          string             `json:"verdict"`
	HasRequiredStack float32            `json:"has_required_stack"`
	FitsLevel        float32            `json:"fits_level"`
	HardBlocker      float32            `json:"hard_blocker"`
	RoleCategory     string             `json:"role_category"`
}

// The caller's personalized feed: eligible scored jobs, best first. Optional verdict
// filter (” = all) and minimum match_pct. Paginated.
func (q *Queries) ForYouFeed(ctx context.Context, arg ForYouFeedParams) ([]ForYouFeedRow, error) {
	rows, err := q.db.Query(ctx, forYouFeed,
		arg.UserID,
		arg.Verdict,
		arg.MinPct,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForYouFeedRow{}
	for rows.Next() {
		var i ForYouFeedRow
		if err := rows.Scan(
			&i.PublicSlug,
			&i.Title,
			&i.Company,
			&i.CompanySlug,
			&i.Location,
			&i.WorkMode,
			&i.PostedAt,
			&i.ClosedAt,
			&i.Skills,
			&i.MatchPct,
			&i.Verdict,
			&i.HasRequiredStack,
			&i.FitsLevel,
			&i.HardBlocker,
			&i.RoleCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserJobScore = `-- name: GetUserJobScore :one
SELECT match_pct, match_raw, match_confidence, role_category, role_confidence,
       has_required_stack, fits_level, hard_blocker, verdict,
       model, score_version, profile_fingerprint, cv_uploaded_at, job_content_hash, scored_at
FROM user_job_scores
WHERE user_id = $1 AND job_id = $2
`

type GetUserJobScoreParams struct {
	UserID int64 `json:"user_id"`
	JobID  int64 `json:"job_id"`
}

type GetUserJobScoreRow struct {
	MatchPct           int16              `json:"match_pct"`
	MatchRaw           float32            `json:"match_raw"`
	MatchConfidence    float32            `json:"match_confidence"`
	RoleCategory       string             `json:"role_category"`
	RoleConfidence     float32            `json:"role_confidence"`
	HasRequiredStack   float32            `json:"has_required_stack"`
	FitsLevel          float32            `json:"fits_level"`
	HardBlocker        float32            `json:"hard_blocker"`
	Verdict            string             `json:"verdict"`
	Model              string             `json:"model"`
	ScoreVersion       int32              `json:"score_version"`
	ProfileFingerprint string             `json:"profile_fingerprint"`
	CvUploadedAt       pgtype.Timestamptz `json:"cv_uploaded_at"`
	JobContentHash     pgtype.Text        `json:"job_content_hash"`
	ScoredAt           pgtype.Timestamptz `json:"scored_at"`
}

// The caller's cached Jev score for one job, with the five staleness stamps. No row =
// never scored (handler falls back to deterministic coverage). The handler compares the
// stamps to live values to decide the stale flag.
func (q *Queries) GetUserJobScore(ctx context.Context, arg GetUserJobScoreParams) (GetUserJobScoreRow, error) {
	row := q.db.QueryRow(ctx, getUserJobScore, arg.UserID, arg.JobID)
	var i GetUserJobScoreRow
	err := row.Scan(
		&i.MatchPct,
		&i.MatchRaw,
		&i.MatchConfidence,
		&i.RoleCategory,
		&i.RoleConfidence,
		&i.HasRequiredStack,
		&i.FitsLevel,
		&i.HardBlocker,
		&i.Verdict,
		&i.Model,
		&i.ScoreVersion,
		&i.ProfileFingerprint,
		&i.CvUploadedAt,
		&i.JobContentHash,
		&i.ScoredAt,
	)
	return i, err
}

const invalidateUserScores = `-- name: InvalidateUserScores :exec
DELETE FROM user_job_scores WHERE user_id = $1
`

// Drop a user's scores after a profile edit or CV upload so they re-score fresh.
func (q *Queries) InvalidateUserScores(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateUserScores, userID)
	return err
}

const recordJevScoreFailure = `-- name: RecordJevScoreFailure :one
UPDATE job_score_outbox
SET attempts   = attempts + 1,
    last_error = $1,
    failed_at  = CASE
                     WHEN $2::boolean
                         THEN CASE WHEN attempts + 1 >= $3::int THEN now() END
                     ELSE CASE
                              WHEN $4::int > 0
                                  AND created_at < now() - make_interval(days => $4::int)
                                  THEN now()
                          END
                 END
WHERE id = $5
RETURNING attempts, failed_at
`

type RecordJevScoreFailureParams struct {
	LastError         string `json:"last_error"`
	PostingAtFault    bool   `json:"posting_at_fault"`
	MaxAttempts       int32  `json:"max_attempts"`
	UpstreamGraceDays int32  `json:"upstream_grace_days"`
	ID                int64  `json:"id"`
}

type RecordJevScoreFailureRow struct {
	Attempts int32              `json:"attempts"`
	FailedAt pgtype.Timestamptz `json:"failed_at"`
}

// Count a failed attempt; dead-letter at max_attempts (posting-fault) or past the
// upstream grace window (outage). Lease left in place as the crash reaper.
func (q *Queries) RecordJevScoreFailure(ctx context.Context, arg RecordJevScoreFailureParams) (RecordJevScoreFailureRow, error) {
	row := q.db.QueryRow(ctx, recordJevScoreFailure,
		arg.LastError,
		arg.PostingAtFault,
		arg.MaxAttempts,
		arg.UpstreamGraceDays,
		arg.ID,
	)
	var i RecordJevScoreFailureRow
	err := row.Scan(&i.Attempts, &i.FailedAt)
	return i, err
}

const upsertUserJobScore = `-- name: UpsertUserJobScore :exec
INSERT INTO user_job_scores (
    user_id, job_id, match_pct, match_raw, match_confidence, role_category, role_confidence,
    has_required_stack, fits_level, hard_blocker, verdict,
    model, score_version, profile_fingerprint, cv_uploaded_at, job_content_hash, scored_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16, now())
ON CONFLICT (user_id, job_id) DO UPDATE SET
    match_pct           = EXCLUDED.match_pct,
    match_raw           = EXCLUDED.match_raw,
    match_confidence    = EXCLUDED.match_confidence,
    role_category       = EXCLUDED.role_category,
    role_confidence     = EXCLUDED.role_confidence,
    has_required_stack  = EXCLUDED.has_required_stack,
    fits_level          = EXCLUDED.fits_level,
    hard_blocker        = EXCLUDED.hard_blocker,
    verdict             = EXCLUDED.verdict,
    model               = EXCLUDED.model,
    score_version       = EXCLUDED.score_version,
    profile_fingerprint = EXCLUDED.profile_fingerprint,
    cv_uploaded_at      = EXCLUDED.cv_uploaded_at,
    job_content_hash    = EXCLUDED.job_content_hash,
    scored_at           = now()
`

type UpsertUserJobScoreParams struct {
	UserID             int64              `json:"user_id"`
	JobID              int64              `json:"job_id"`
	MatchPct           int16              `json:"match_pct"`
	MatchRaw           float32            `json:"match_raw"`
	MatchConfidence    float32            `json:"match_confidence"`
	RoleCategory       string             `json:"role_category"`
	RoleConfidence     float32            `json:"role_confidence"`
	HasRequiredStack   float32            `json:"has_required_stack"`
	FitsLevel          float32            `json:"fits_level"`
	HardBlocker        float32            `json:"hard_blocker"`
	Verdict            string             `json:"verdict"`
	Model              string             `json:"model"`
	ScoreVersion       int32              `json:"score_version"`
	ProfileFingerprint string             `json:"profile_fingerprint"`
	CvUploadedAt       pgtype.Timestamptz `json:"cv_uploaded_at"`
	JobContentHash     pgtype.Text        `json:"job_content_hash"`
}

// Create-or-replace the score for a (user, job). Composite PK makes it idempotent.
func (q *Queries) UpsertUserJobScore(ctx context.Context, arg UpsertUserJobScoreParams) error {
	_, err := q.db.Exec(ctx, upsertUserJobScore,
		arg.UserID,
		arg.JobID,
		arg.MatchPct,
		arg.MatchRaw,
		arg.MatchConfidence,
		arg.RoleCategory,
		arg.RoleConfidence,
		arg.HasRequiredStack,
		arg.FitsLevel,
		arg.HardBlocker,
		arg.Verdict,
		arg.Model,
		arg.ScoreVersion,
		arg.ProfileFingerprint,
		arg.CvUploadedAt,
		arg.JobContentHash,
	)
	return err
}
