// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_profiles.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserProfile = `-- name: DeleteUserProfile :execrows
DELETE FROM user_profiles
WHERE user_id = $1
`

// Remove the caller's profile. Returns the affected row count (0 when none existed); the
// handler treats delete as idempotent (204 either way).
func (q *Queries) DeleteUserProfile(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserProfile, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, skills, created_at, updated_at, specializations, location_preferences, excluded_skills, seniorities, excluded_sources, excluded_companies FROM user_profiles
WHERE user_id = $1
`

// The caller's single profile, keyed by user_id. No matching row means the user has not
// saved a profile yet (the handler maps that to a null payload / 404 on sub-resources).
func (q *Queries) GetUserProfile(ctx context.Context, userID int64) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Specializations,
		&i.LocationPreferences,
		&i.ExcludedSkills,
		&i.Seniorities,
		&i.ExcludedSources,
		&i.ExcludedCompanies,
	)
	return i, err
}

const listAllUserProfiles = `-- name: ListAllUserProfiles :many
SELECT user_id, specializations, skills, seniorities, excluded_sources, excluded_companies, location_preferences
FROM user_profiles
`

type ListAllUserProfilesRow struct {
	UserID              int64           `json:"user_id"`
	Specializations     []string        `json:"specializations"`
	Skills              []string        `json:"skills"`
	Seniorities         []string        `json:"seniorities"`
	ExcludedSources     []string        `json:"excluded_sources"`
	ExcludedCompanies   []string        `json:"excluded_companies"`
	LocationPreferences json.RawMessage `json:"location_preferences"`
}

// Every saved profile, for cmd/jevscore's per-run enqueue pass: it walks every profile
// and issues one coarse EnqueueJevScoresForProfile per user. Selects only the columns
// that pass drives (specializations/seniorities feed the coarse filter, skills feed the
// profile fingerprint, excluded_sources/excluded_companies feed the coarse exclude
// filter, location_preferences feeds the fingerprint). user_profiles is a one-row-per-user
// table with no expected high cardinality, so a full unpaged scan is the deliberately
// simple choice here; revisit with a keyset cursor if that stops being true.
func (q *Queries) ListAllUserProfiles(ctx context.Context) ([]ListAllUserProfilesRow, error) {
	rows, err := q.db.Query(ctx, listAllUserProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUserProfilesRow{}
	for rows.Next() {
		var i ListAllUserProfilesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Specializations,
			&i.Skills,
			&i.Seniorities,
			&i.ExcludedSources,
			&i.ExcludedCompanies,
			&i.LocationPreferences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProfilesExcludedSkills = `-- name: ListUserProfilesExcludedSkills :many
SELECT user_id, excluded_skills FROM user_profiles
WHERE user_id = ANY($1::bigint[])
`

type ListUserProfilesExcludedSkillsRow struct {
	UserID         int64    `json:"user_id"`
	ExcludedSkills []string `json:"excluded_skills"`
}

// excluded_skills for a batch of users, one round trip regardless of batch size. A user_id
// with no profile row simply produces no row here; the caller treats absence as an empty
// exclude set.
func (q *Queries) ListUserProfilesExcludedSkills(ctx context.Context, userIds []int64) ([]ListUserProfilesExcludedSkillsRow, error) {
	rows, err := q.db.Query(ctx, listUserProfilesExcludedSkills, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProfilesExcludedSkillsRow{}
	for rows.Next() {
		var i ListUserProfilesExcludedSkillsRow
		if err := rows.Scan(&i.UserID, &i.ExcludedSkills); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (user_id, specializations, skills, seniorities, excluded_skills, excluded_sources, excluded_companies, location_preferences)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE
SET specializations      = EXCLUDED.specializations,
    skills               = EXCLUDED.skills,
    seniorities          = EXCLUDED.seniorities,
    excluded_skills      = EXCLUDED.excluded_skills,
    excluded_sources     = EXCLUDED.excluded_sources,
    excluded_companies   = EXCLUDED.excluded_companies,
    location_preferences = EXCLUDED.location_preferences,
    updated_at           = now()
RETURNING user_id, skills, created_at, updated_at, specializations, location_preferences, excluded_skills, seniorities, excluded_sources, excluded_companies
`

type UpsertUserProfileParams struct {
	UserID              int64           `json:"user_id"`
	Specializations     []string        `json:"specializations"`
	Skills              []string        `json:"skills"`
	Seniorities         []string        `json:"seniorities"`
	ExcludedSkills      []string        `json:"excluded_skills"`
	ExcludedSources     []string        `json:"excluded_sources"`
	ExcludedCompanies   []string        `json:"excluded_companies"`
	LocationPreferences json.RawMessage `json:"location_preferences"`
}

// Create-or-replace the user's one profile. The PRIMARY KEY (user_id) makes this an
// idempotent upsert: first save inserts, later saves overwrite specializations/skills/
// seniorities/excluded_skills/excluded_sources/excluded_companies/location_preferences and
// bump updated_at. All fields are already normalized by the service; seniorities,
// excluded_skills, excluded_sources and excluded_companies may be empty;
// location_preferences is a validated JSONB block or NULL (no preferences).
func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.UserID,
		arg.Specializations,
		arg.Skills,
		arg.Seniorities,
		arg.ExcludedSkills,
		arg.ExcludedSources,
		arg.ExcludedCompanies,
		arg.LocationPreferences,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Specializations,
		&i.LocationPreferences,
		&i.ExcludedSkills,
		&i.Seniorities,
		&i.ExcludedSources,
		&i.ExcludedCompanies,
	)
	return i, err
}

const upsertUserProfileIfUnchanged = `-- name: UpsertUserProfileIfUnchanged :one
UPDATE user_profiles
SET specializations      = $2,
    skills               = $3,
    seniorities          = $4,
    excluded_skills      = $5,
    excluded_sources     = $6,
    excluded_companies   = $7,
    location_preferences = $8,
    updated_at           = now()
WHERE user_id = $1 AND updated_at = $9
RETURNING user_id, skills, created_at, updated_at, specializations, location_preferences, excluded_skills, seniorities, excluded_sources, excluded_companies
`

type UpsertUserProfileIfUnchangedParams struct {
	UserID              int64              `json:"user_id"`
	Specializations     []string           `json:"specializations"`
	Skills              []string           `json:"skills"`
	Seniorities         []string           `json:"seniorities"`
	ExcludedSkills      []string           `json:"excluded_skills"`
	ExcludedSources     []string           `json:"excluded_sources"`
	ExcludedCompanies   []string           `json:"excluded_companies"`
	LocationPreferences json.RawMessage    `json:"location_preferences"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Same write as UpsertUserProfile, guarded on the row's updated_at still matching what the
// caller read. Used by MergeSkills, whose merge (which fields to keep, which skills to add)
// is computed in Go from a prior Get, outside any transaction: a Save() landing in that gap
// must not be silently clobbered by a write built from a now-stale snapshot. No matching row
// (updated_at moved, or the profile was deleted) returns zero rows; the caller re-reads and
// retries rather than overwriting blind.
func (q *Queries) UpsertUserProfileIfUnchanged(ctx context.Context, arg UpsertUserProfileIfUnchangedParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfileIfUnchanged,
		arg.UserID,
		arg.Specializations,
		arg.Skills,
		arg.Seniorities,
		arg.ExcludedSkills,
		arg.ExcludedSources,
		arg.ExcludedCompanies,
		arg.LocationPreferences,
		arg.UpdatedAt,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Specializations,
		&i.LocationPreferences,
		&i.ExcludedSkills,
		&i.Seniorities,
		&i.ExcludedSources,
		&i.ExcludedCompanies,
	)
	return i, err
}
